// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['desktop']['App']['CancelDownload'](arg1);
}

export function CheckForUpdate() {
  return window['go']['desktop']['App']['CheckForUpdate']();
}

export function CheckYtDlp() {
  return window['go']['desktop']['App']['CheckYtDlp']();
}

export function ClearCompleted() {
  return window['go']['desktop']['App']['ClearCompleted']();
}

export function GetAboutInfo() {
  return window['go']['desktop']['App']['GetAboutInfo']();
}

export function GetCurrentVersion() {
  return window['go']['desktop']['App']['GetCurrentVersion']();
}

export function GetDefaultDownloadDir() {
  return window['go']['desktop']['App']['GetDefaultDownloadDir']();
}

export function GetDepStatus() {
  return window['go']['desktop']['App']['GetDepStatus']();
}

export function GetDiagnosticInfo() {
  return window['go']['desktop']['App']['GetDiagnosticInfo']();
}

export function GetDownloads() {
  return window['go']['desktop']['App']['GetDownloads']();
}

export function GetFormats(arg1) {
  return window['go']['desktop']['App']['GetFormats'](arg1);
}

export function GetLang() {
  return window['go']['desktop']['App']['GetLang']();
}

export function GetPlaylistInfo(arg1) {
  return window['go']['desktop']['App']['GetPlaylistInfo'](arg1);
}

export function GetSettings() {
  return window['go']['desktop']['App']['GetSettings']();
}

export function GetVideoInfo(arg1) {
  return window['go']['desktop']['App']['GetVideoInfo'](arg1);
}

export function IsFirstRun() {
  return window['go']['desktop']['App']['IsFirstRun']();
}

export function NeedsCookieConfig() {
  return window['go']['desktop']['App']['NeedsCookieConfig']();
}

export function OpenFile(arg1) {
  return window['go']['desktop']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['desktop']['App']['OpenFolder'](arg1);
}

export function OpenReleasePage() {
  return window['go']['desktop']['App']['OpenReleasePage']();
}

export function RemoveDownload(arg1) {
  return window['go']['desktop']['App']['RemoveDownload'](arg1);
}

export function ResetSettings() {
  return window['go']['desktop']['App']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['desktop']['App']['SaveSettings'](arg1);
}

export function SelectCookiesFile() {
  return window['go']['desktop']['App']['SelectCookiesFile']();
}

export function SelectFolder() {
  return window['go']['desktop']['App']['SelectFolder']();
}

export function SetLang(arg1) {
  return window['go']['desktop']['App']['SetLang'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['desktop']['App']['StartDownload'](arg1);
}

export function UpdateDeno() {
  return window['go']['desktop']['App']['UpdateDeno']();
}

export function UpdateYtDlp() {
  return window['go']['desktop']['App']['UpdateYtDlp']();
}
