// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<desktop.UpdateInfo>;

export function CheckYtDlp():Promise<desktop.YtDlpStatus>;

export function ClearCompleted():Promise<void>;

export function GetAboutInfo():Promise<desktop.AboutInfo>;

export function GetCurrentVersion():Promise<string>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetDepStatus():Promise<desktop.DepStatus>;

export function GetDiagnosticInfo():Promise<desktop.DiagnosticInfo>;

export function GetDownloads():Promise<Array<desktop.DownloadTask>>;

export function GetFormats(arg1:string):Promise<desktop.FormatInfo>;

export function GetLang():Promise<string>;

export function GetPlaylistInfo(arg1:string):Promise<desktop.PlaylistInfo>;

export function GetSettings():Promise<desktop.Settings>;

export function GetVideoInfo(arg1:string):Promise<desktop.VideoInfo>;

export function IsFirstRun():Promise<boolean>;

export function NeedsCookieConfig():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenReleasePage():Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveSettings(arg1:desktop.Settings):Promise<void>;

export function SelectCookiesFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetLang(arg1:string):Promise<void>;

export function StartDownload(arg1:desktop.DownloadRequest):Promise<string>;

export function UpdateDeno():Promise<string>;

export function UpdateYtDlp():Promise<string>;
