// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckYtDlp() {
  return window['go']['main']['App']['CheckYtDlp']();
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function GetDefaultDownloadDir() {
  return window['go']['main']['App']['GetDefaultDownloadDir']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetPlaylistInfo(arg1) {
  return window['go']['main']['App']['GetPlaylistInfo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
