// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckYtDlp():Promise<main.YtDlpStatus>;

export function ClearCompleted():Promise<void>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetDiagnosticInfo():Promise<main.DiagnosticInfo>;

export function GetDownloads():Promise<Array<main.DownloadTask>>;

export function GetFormats(arg1:string):Promise<main.FormatInfo>;

export function GetLang():Promise<string>;

export function GetPlaylistInfo(arg1:string):Promise<main.PlaylistInfo>;

export function GetSettings():Promise<main.Settings>;

export function GetVideoInfo(arg1:string):Promise<main.VideoInfo>;

export function IsFirstRun():Promise<boolean>;

export function NeedsCookieConfig():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function ResetSettings():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectCookiesFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetLang(arg1:string):Promise<void>;

export function StartDownload(arg1:main.DownloadRequest):Promise<string>;

export function UpdateYtDlp():Promise<string>;
